feat(api): add version endpoint

diff --git a/.github/workflows/verify.yaml b/.github/workflows/verify.yaml
--- a/.github/workflows/verify.yaml
+++ b/.github/workflows/verify.yaml
@@ -6,10 +6,10 @@ on:
   pull_request:
     branches: [ main, refactor/* ]
     paths-ignore:
-      - '**.md'
-      - 'docs/**'
-      - 'CODEOWNERS'
-      - 'LICENSE'
+      - "**.md"
+      - "docs/**"
+      - "CODEOWNERS"
+      - "LICENSE"
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
@@ -37,6 +37,31 @@ jobs:
 
       - name: Run Javadoc
         run: ./gradlew javadoc
+
+  Verify-Api-Version:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - name: Inspect changeset if version file changed
+        run: |
+          # main branch is not checked out by default
+          git fetch origin main:main
+
+          # check if there was a change any of the management API modules. the last "grep" parses the result of "wc" into a number
+          apiChanges=$(git diff --name-status main | grep "extensions/control-plane/api/management-api" | wc -l | grep -o "[0-9]\+")
+          if [[ $apiChanges = 0 ]]; then
+            echo "There were no changes in the Management API"
+          else 
+            echo "There are $apiChanges changed files in the Management API, will check if api-version.json was modified."
+            # if so, check if the changeset also contains the `api-version.json` file
+            changes=$(git diff --name-status main | grep "api-version.json" |  wc -l | grep -o "[0-9]\+")
+            if [[ $changes < 1 ]]; then
+              echo "::error file=./extensions/common/api/management-api-configuration/src/main/resources/api-version.json,line=1::Bumping the version is required after a change to the Management API"
+              exit 1;
+            fi
+          fi
+  
+  
 
   Unit-Tests:
     runs-on: ubuntu-latest
